#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR/03-智能助理"
echo "========================================="
echo "  智慧宝库 v2.1"
echo "========================================="
echo "  方式一：直接打开文件"
echo "    open $DIR/03-智能助理/index.html"
echo ""
echo "  方式二：启动简易 HTTP 服务（手机可访问）"
echo "    电脑上执行：python3 -m http.server 8080"
echo "    然后手机访问 http://你电脑IP:8080"
echo "========================================="
open "$DIR/03-智能助理/index.html"
